### ISSUE TITLE
What is simulation backend?

### ISSUE THREAD

**Issue by quchongqi** [syne-tune/syne-tune#866]
Hello,I want to know what  Simulation backend is.
My understanding is this: Simulation backend use already existing tabulated benchmarks dataset to train a surrogate model and predict performance of the model that require hyperparameters to be tuned after the surrogate model training is complete. This does not involve actual training and cross-validation on models that require hyperparameter tuning. So using simulation backend is very fast,but it is not true hyperparameter tuning.
I don't know if my understanding is correct.

**Comment by aaronkl** [comment]
Hey, thanks for your interest in Syne Tune. Yes, your understanding is generally correct. The simulator backend uses existing surrogate/tabular benchmarks to emulate an expensive asynchronous parallel hyperparameter optimization process. This is not trivial, since different hyperparameter configurations require different amounts of time to evaluate in a real setting, and the order in which they finish influences the decision-making process. You are right that this is not a real HPO problem, but as shown in multiple papers, it closely resembles real problems while requiring orders of magnitude less compute.

**Comment by quchongqi** [comment]
Thank you for the clarification and for confirming my understanding of Syne Tune.
